# 工作流名称
name: Deploy VitePress site to Pages

# 触发条件
on:
  # 当代码推送到 main 分支时触发
  push:
    branches: [main]
  # 允许你从 GitHub Actions 页面手动触发部署
  workflow_dispatch:

# 为 GITHUB_TOKEN 设置权限，以便部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 确保同一时间只有一个部署任务在运行
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建任务
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 如果启用了 VitePress 的 lastUpdated 功能，此设置可以获取完整的 Git 历史
          fetch-depth: 0

      - name: 安装 Node
        uses: actions/setup-node@v4
        with:
          cache: npm # 如果使用 pnpm/yarn，请修改为相应名称
          cache-dependency-path: 'package.json'  # 不使用锁文件

      - name: 安装 Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci
        env:
          # 或者
          CI: 'true'  # CI 环境下 Husky 会自动跳过

      - name: Build with VitePress
        run: npm run docs:build # 或你项目定义的构建命令

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist # 构建输出目录

  # 部署任务
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
