# 工作流名称
name: npm release

# 触发条件
on:
  # 当发布 Release 时触发
  release:
    types: [published]

  # 允许你从 GitHub Actions 页面手动触发
  workflow_dispatch:

# 为 GITHUB_TOKEN 设置权限，以便部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 确保同一时间只有一个部署任务在运行
concurrency:
  group: release
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 安装 Node
        uses: actions/setup-node@v6
        with:
          cache: npm
          cache-dependency-path: "package.json"
          # 设置 npm registry 和认证
          # registry-url: 'https://registry.npmjs.org'

      - name: 安装 dependencies
        run: npm install
        env:
          CI: "true"

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          # 从 GitHub Secrets 读取 npm token
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
